from django.shortcuts import render, redirect
from ..bungie_api.api_client import BungieError, AuthorizationHandler


def login(response):
    auth_data = None # OAuth2 data

    if response.method == 'POST' and 'request_auth_button' in response.POST:
        generate_authentication_link(response)
    
    if response.method == 'POST' and 'auth_button' in response.POST: # TODO: Return OAuth2 data and pass them to view in a variable.
        get_authorization_token(response)
        return redirect('main:overview')
    return render(response, 'main/authentication/login.html', {
        'authorization_data': auth_data
    })

def logout(response):
    return render(response, 'main/authentication/logout.html', {})


def get_character_data(request):
    pass

def generate_authentication_link(request):
    '''
    Redirect user to Bungie's authentication page.\n
    :param request: data from view form.
    '''
    import webbrowser
    webbrowser.open_new_tab(AuthorizationHandler.generate_authentication_link())

def get_authorization_token(request):
    '''
    Takes a link generated by authenticating via Bungie's authentication page.
    '''
    try:
        request.session['authorization'] = AuthorizationHandler.get_token(request.POST["redirect_input"])
        print(request.session['authorization'])
        return True # redirect must be used in view function
    except BungieError as e:
        print(e)